### PR TITLE
Add unlimited max_tokens

### PR DESCRIPTION
**Pull request by jm12138**
* Add a feature with unlimited max_tokens that is enabled when max_tokens <= 0. 

* Similar to this parameter in llama.cpp: 

https://github.com/ggerganov/llama.cpp/blob/180b693a47b6b825288ef9f2c39d24b6eea4eea6/examples/common.cpp#L230

### CODE REVIEW

**Comment by Aqirito** [comment]
is this will be merged?

**Comment by gjmulder** [comment]
@abetlen ?

**Comment by BakaKiller** [comment]
Up ! This would be really great !

**Comment by abetlen** [comment]
@jm12138 thanks for the contribution, sorry took so long to get to this! LGTM

**Pull request merged**
