### PR TITLE
add `mul_mat_q` parameter

### PR DESCRIPTION
**Pull request by bretello**
- add `mul_mat_q` parameter
- Update llama.cpp

### CODE REVIEW

**Comment by bretello** [comment]
Adding some context: trying to load Llama 70b on a M1 Macbook resulted in a segfault.

The first commit in this PR fixes this segfault, possibly caused by the boolean flags not being interpreted correctly due to  `mul_mat_q` missing.

The second commit updates `llama.cpp`. Without this change loading/inference with a 70b model would result in the following assertion failures:
```console
GGML_ASSERT: llama-cpp-python/vendor/llama.cpp/ggml-metal.m:612: ne02 == ne12
GGML_ASSERT:  llama-cpp-python/vendor/llama.cpp/ggml-metal.m:612: ne02 == ne12
GGML_ASSERT:  llama-cpp-python/vendor/llama.cpp/ggml-metal.m:612: ne02 == ne12
```
Note that this only happened with the 70b model

**Comment by Dampfinchen** [comment]
Yes, this is a very important change. Prompt processing speed is a little faster for non-k variants and it saves a lot of VRAM. Right now k-quants are slower but this is going to change soon enough.

**Comment by hajowieland** [comment]
Any ETA when this will be merged? Currently the `llama-2-70b-chat.ggmlv3.q4_0.bin` model can not be used because of the segfaults / assertion failures.
Thanks @bretello for your work!

**Comment by dillfrescott** [comment]
I am still getting this error when attempting to run 70B models. Please help

**Pull request merged**
