### PR TITLE
Add doc string for n_gpu_layers argument and make -1 offload all layers

### PR DESCRIPTION
**Pull request by aliencaocao**

### CODE REVIEW

**Comment by gaby** [comment]
If it wasnt for this, i wouldnt know you can use `-1`

**Comment by aliencaocao** [comment]
Actually -1 is not tested...it works for you?

**Comment by gaby** [comment]
> Actually -1 is not tested...it works for you?

I haven't tried it

**Comment by aliencaocao** [comment]
Well now it should work

**Review by abetlen — APPROVED** [review]

**Pull request merged**
