### PR TITLE
Feat: adding `rpc_servers` parameter to `Llama` class

### LINKED ISSUE #1455: Add RPC backend support

### PR DESCRIPTION
**Pull request by chraac**
This PR include those changes:

- Add `rpc_servers` to `Llama`, to bypass the `rpc_servers` to llama.cpp lib
- In Makefile, add item to enable `LLAMA_RPC` flag
- Update the llama.cpp submodule reference to latest version

Tested on my machine, work as expected

Closes #1455

### CODE REVIEW

**Comment by abetlen** [comment]
@chraac great work! Could you also include the build flags in the README as well as maybe a small section on running the rpc servers?

**Comment by chraac** [comment]
> @chraac great work! Could you also include the build flags in the README as well as maybe a small section on running the rpc servers?

yeah, sure, will add to readme, thanks for the reply!

**Comment by chraac** [comment]
@abetlen add a section in `README.md` about how to build the rpc backend.

**Comment by chraac** [comment]
@abetlen , could you have another look in convenient please? have added a section regarding how to build the RPC backend package.

**Comment by juanjfrancisco** [comment]
Hi, I apologize for asking this here, but I'm trying to understand how to use the RPC_SERVERS functionality to enable inference across multiple machines. Can anyone help clarify this for me or give me an example?. Thanks in advance.

**Comment by statchamber** [comment]
How do I use this...?

**Comment by chraac** [comment]
Hi @juanjfrancisco  @statchamber , sorry for the inconvient here, currently the `GGML_RPC` flag is off by default, sop you maight need to install the python package from the source:

1. clone the repo: `git clone https://github.com/abetlen/llama-cpp-python.git`
2. For rpc client, which is the endpoint that make the rpc request, could be installed by following command into python env: 
   `CMAKE_ARGS='-DGGML_RPC=on -DGGML_OPENMP=on' python3 -m pip install --verbose -e .`
3. For the rpc server that will actually execute the rpc request, could be installed by:
    `cmake -DLLAMA_RPC=ON -DLLAMA_CUDA=ON .. && cmake --build . --config Release`

**Pull request merged**
