### PR TITLE
Support SPM infill

### PR DESCRIPTION
**Pull request by CISC**
Add `spm_infill` option to perform infill in the Suffix/Prefix/Middle pattern instead of Prefix/Suffix/Middle as some models (like the new `Codestral`) prefer this.

Also added a tokenizer hack to remove leading space in suffix to improve inference, tested on several different tokenizers/vocabs with success.

### CODE REVIEW

**Comment by CISC** [comment]
Actually, since I ended up not using them there let's make it simple and remove them from that PR and add them here.

**Comment by CISC** [comment]
My [Codestral GGUFs](https://huggingface.co/CISCai/Codestral-22B-v0.1-SOTA-GGUF) are up for those who wish to test with this option.

NOTE: It requires ggerganov/llama.cpp#7644 to not insert garbage `middle` token!

**Comment by abetlen** [comment]
@CISC looks good overall, do you mind adding something minimal to `/examples` that would help me review this and demonstrat the FIM API?

**Comment by CISC** [comment]
Sure, no problem.

**Comment by CISC** [comment]
@abetlen Example added.

**Pull request merged**
