### PR TITLE
Fix UnicodeDecodeError permanently

### PR DESCRIPTION
**Pull request by SagsMug**
https://docs.python.org/3/library/codecs.html#error-handlers

This detects a multibyte UTF8 character, and doesn't return if its incomplete.
If there otherwise wasn't enough tokens or the model somehow returns invalid bytes, we use errors="ignore" to remove invalid characters.
Ascii example:
> 'German ß, ♬'.encode(encoding='ascii', errors="ignore")
> b'German , '

But there will never be thrown a decode or encode error.

Fixes:
https://github.com/abetlen/llama-cpp-python/issues/36
https://github.com/abetlen/llama-cpp-python/issues/57
https://github.com/abetlen/llama-cpp-python/issues/100
https://github.com/abetlen/llama-cpp-python/issues/116

### CODE REVIEW

**Comment by abetlen** [comment]
Thanks @SagsMug, I'll take a look at this and weigh against #55 I think this better preserves streaming functionality.

So is this bug just due to the fact that the Llama vocabulary includes token which are not valid utf-8 strings?

**Comment by SagsMug** [comment]
> Thanks @SagsMug, I'll take a look at this and weigh against #55 I think this better preserves streaming functionality.
> 
> So is this bug just due to the fact that the Llama vocabulary includes token which are not valid utf-8 strings?

According to this:
https://github.com/ggerganov/llama.cpp/pull/73#issuecomment-1465469224
It does indeed stem from some characters needing multiple tokens.

They supposedly fixed this by changing the model converter in https://github.com/ggerganov/llama.cpp/pull/79
But given we still encounter this issue, maybe not.

```
> import llama_cpp
> lparams = llama_cpp.llama_context_default_params()
> ctx = llama_cpp.llama_init_from_file("./models/7B/ggml-model-q4_0.bin", lparams)
> def _tokenize(prompt, bos=True):
 _arr = (llama_cpp.llama_token * (len(prompt) + 1))()
 _n = llama_cpp.llama_tokenize(ctx, prompt.encode("utf8"), _arr, len(_arr), bos)
 return _arr[:_n]
> _tokenize("😀", False)
llama_tokenize: too many tokens
[]
```

I would speculate that the only real solution is to save invalid tokens until a valid output occurs.
But this works alright until that happens.

**Comment by SagsMug** [comment]
> Thanks @SagsMug, I'll take a look at this and weigh against #55 I think this better preserves streaming functionality.
> 
> So is this bug just due to the fact that the Llama vocabulary includes token which are not valid utf-8 strings?

I have added a check that detects a multi-byte UTF8, and waits accordingly.
It

> Thanks @SagsMug, I'll take a look at this and weigh against #55 I think this better preserves streaming functionality.
> 
> So is this bug just due to the fact that the Llama vocabulary includes token which are not valid utf-8 strings?

I have tried to address UTF8 properly by detecting multibytes and waiting for their completion.
Please check that it's satisfactory.
I have also kept the errors = "ignore" as a precaution.

**Comment by abetlen** [comment]
@SagsMug can we reduce the use of `errors="ignore"` to just bare minimum to catch detokenize issues, ie. we probably don't need it for prompts and such.

**Comment by SagsMug** [comment]
> @SagsMug can we reduce the use of `errors="ignore"` to just bare minimum to catch detokenize issues, ie. we probably don't need it for prompts and such.

I have removed a bunch of cases and add a test for this.
Im pretty sure the rest are necessary, but please check

**Review by abetlen — APPROVED** [review]

**Comment by mozzipa** [comment]
Because of errors from Llama.generate() and low level api, I use below code snippet. 
How about to integrate it?

```
                if not input_noecho:
                    for id in tokens:
                        detoken = llama_cpp.Llama.detokenize(self=self,tokens=[id])
                        byte_list.append(detoken)
                        gen_tokens += 1
                        try:
                            combine = b''.join(byte_list)
                            letter = combine.decode("utf-8")
                            # print(letter, end="",flush=True)
                            # yield print(letter, end="",flush=True)
                            yield letter
                            if gen_tokens > n_predict:
                                gen_tokens = 0
                                # llama_cpp.llama_free()
                                break
                            byte_list = []
                            
                        except:
                            pass
```

**Pull request merged**
