### PR TITLE
Binary wheels

### PR DESCRIPTION
**Pull request by abetlen**
Adds initial support for releasing binary wheels. Uses github-pages to publish one index per backend (CPU, Metal, CUDA, etc) to a static site.

Planned release tags for this PR (because I can test these):
- `cpu`
- `cu121`
- `cu122`
- `cu123`
- `metal`

# Usage (won't work until merge)

To install a cpu only image

```bash
pip install llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu
```

# TODO

- Port the release workflows from https://github.com/jllllll/llama-cpp-python-cuBLAS-wheels
- Reduce number of wheels produced per tag

Related: #1178, #243 and #741

### CODE REVIEW

**Comment by oobabooga** [comment]
I have been building llama-cpp-python wheels for each new release in my fork of jllllll's repository:

https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/actions

It has some minor changes to avoid hitting rate limit errors. It also builds for all Mac versions (I think jllllll removed Mac 11 due to an error that used to happen but doesn't anymore).

**Comment by abetlen** [comment]
@oobabooga yes I saw that, really appreciate you guys carrying that! I'll probably just port over those release workflows and modify them so they name the release based on the version and backend tag ie `v0.2.55-cu121` or something like that.

It would be great if we can reduce the number of builds per release though.

**Comment by ElliottDyson** [comment]
Any chance intel arc binaries could also be added? Thanks

**Comment by ElliottDyson** [comment]
> Any chance intel arc binaries could also be added? Thanks

With Intel's new IPEX-LLM release this is no longer necessary. A pointer to this however might be useful as it isn't well advertised.

**Pull request merged**
