### PR TITLE
Support multiple chat templates - step 1

### PR DESCRIPTION
**Pull request by CISC**
As a first step towards #1336, allow user to to select template from metadata with chat_format parameter in the form of `chat_template.name`.

### CODE REVIEW

**Comment by abetlen** [comment]
@CISC thank you I'll review this weekend!

**Comment by abetlen** [comment]
@CISC sorry for the delay in reviewing, one thought I had is that I'm a little nervous about registering these templates globally on model load, this seems like a side-effect that will cause some headaches if users are unaware.

**Comment by CISC** [comment]
Sure, I get that, it also just occurred to me that this will wreak havoc if a user loads more than one model with chat template metadata. :(

Maybe register it per-model somehow?

**Comment by CISC** [comment]
@abetlen How about this? Does not clobber global registry, but still easily accessible for run-time switch.

**Comment by abetlen** [comment]
@CISC perfect, I did update `chat_handlers` -> `_chat_handlers` to keep it private for now but otherwise it looks good to me.

**Pull request merged**
