### PR TITLE
Diskcache implementation for llama state.

### PR DESCRIPTION
**Pull request by Maximilian-Winter**

### CODE REVIEW

**Comment by abetlen** [comment]
1. Can you add diskcache to the setup.py and pyproject.toml dependencies?
2. Is it possible to support both options? Ie have a filesysystem cache and a ram cache

**Comment by Maximilian-Winter** [comment]
@abetlen Will add all the stuff later today!

**Comment by Maximilian-Winter** [comment]
@abetlen Have added a LlamaCache base class and RAM and Disk child classes!

**Review by Jchang4 — APPROVED** [review]
LGTM! Thank you!

**Pull request merged**
