### PR TITLE
Support all types of GGUF metadata

### PR DESCRIPTION
**Pull request by ddh0**
Relevant issue: [#1495: `_LlamaModel.metadata()` does not return `tokenizer.ggml.tokens`](https://github.com/abetlen/llama-cpp-python/issues/1495)

This PR implements support for reading arrays from GGUF metadata from GGUFv2 and GGUFv3 files according to [Georgi Gerganov's format spec for GGUF](https://github.com/ggerganov/ggml/blob/master/docs/gguf.md). I've tested it and it works with GGUFv2 and GGUFv3 models and all types of metadata.

The API is unchanged - just call the `_LlamaModel.metadata()` method the same as before.

I also changed the way metadata is displayed when loading a model with `verbose=True`, because some arrays in metadata can be hundreds of thousands of items long (vocabulary, etc). So now each key and value is printed on its own line, and and value over 60 characters is truncated with `...`.

cc: @abetlen @CISC - I would appreciate any feedback :)

---

Example output when loading a model:

<details>
<summary> Click to expand full output </summary>

```
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import llama_cpp
>>> Llama = llama_cpp.Llama('./models/Meta-Llama-3-8B-Instruct-q8_0.gguf')
llama_model_loader: loaded meta data with 22 key-value pairs and 291 tensors from ./models/Meta-Llama-3-8B-Instruct-q8_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = Meta-Llama-3-8B-Instruct
llama_model_loader: - kv   2:                          llama.block_count u32              = 32
llama_model_loader: - kv   3:                       llama.context_length u32              = 8192
llama_model_loader: - kv   4:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   7:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 7
llama_model_loader: - kv  11:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  12:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  14:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 128001
llama_model_loader: - kv  20:                    tokenizer.chat_template str              = {% set loop_messages = messages %}{% ...
llama_model_loader: - kv  21:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q8_0:  226 tensors
llm_load_vocab: special tokens cache size = 256
llm_load_vocab: token to piece cache size = 1.5928 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 128256
llm_load_print_meta: n_merges         = 280147
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 8B
llm_load_print_meta: model ftype      = Q8_0
llm_load_print_meta: model params     = 8.03 B
llm_load_print_meta: model size       = 7.95 GiB (8.50 BPW) 
llm_load_print_meta: general.name     = Meta-Llama-3-8B-Instruct
llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
llm_load_print_meta: EOS token        = 128001 '<|end_of_text|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4060 Ti, compute capability 8.9, VMM: yes
llm_load_tensors: ggml ctx size =    0.15 MiB
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/33 layers to GPU
llm_load_tensors:        CPU buffer size =  8137.64 MiB
.........................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 500000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =    64.00 MiB
llama_new_context_with_model: KV self size  =   64.00 MiB, K (f16):   32.00 MiB, V (f16):   32.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     0.49 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =   790.81 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =     9.01 MiB
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 356
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | AVX512_BF16 = 1 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | 
Model metadata:
  general.architecture: 'llama'
  general.name: 'Meta-Llama-3-8B-Instruct'
  llama.block_count: 32
  llama.context_length: 8192
  llama.embedding_length: 4096
  llama.feed_forward_length: 14336
  llama.attention.head_count: 32
  llama.attention.head_count_kv: 8
  llama.rope.freq_base: 500000.0
  llama.attention.layer_norm_rms_epsilon: 9.999999747378752e-06
  general.file_type: 7
  llama.vocab_size: 128256
  llama.rope.dimension_count: 128
  tokenizer.ggml.model: 'gpt2'
  tokenizer.ggml.pre: 'llama-bpe'
  tokenizer.ggml.tokens: ['!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',',...
  tokenizer.ggml.token_type: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
  tokenizer.ggml.merges: ['Ġ Ġ', 'Ġ ĠĠĠ', 'ĠĠ ĠĠ', 'ĠĠĠ Ġ', 'i n', 'Ġ t', 'Ġ ĠĠĠĠĠĠĠ'...
  tokenizer.ggml.bos_token_id: 128000
  tokenizer.ggml.eos_token_id: 128001
  tokenizer.chat_template: "{% set loop_messages = messages %}{% for message in loop_me...
  general.quantization_version: 2
Available chat formats from metadata: chat_template.default
Guessed chat format: llama-3
>>> 

```
</details>

### CODE REVIEW

**Comment by ddh0** [comment]
```python
>>> for k in metadata: print(f"{k} has type {type(metadata[k])}")
... 
general.architecture has type <class 'str'>
general.name has type <class 'str'>
llama.block_count has type <class 'int'>
llama.context_length has type <class 'int'>
llama.embedding_length has type <class 'int'>
llama.feed_forward_length has type <class 'int'>
llama.attention.head_count has type <class 'int'>
llama.attention.head_count_kv has type <class 'int'>
llama.rope.freq_base has type <class 'float'>
llama.attention.layer_norm_rms_epsilon has type <class 'float'>
general.file_type has type <class 'int'>
llama.vocab_size has type <class 'int'>
llama.rope.dimension_count has type <class 'int'>
tokenizer.ggml.model has type <class 'str'>
tokenizer.ggml.pre has type <class 'str'>
tokenizer.ggml.tokens has type <class 'list'>
tokenizer.ggml.token_type has type <class 'list'>
tokenizer.ggml.merges has type <class 'list'>
tokenizer.ggml.bos_token_id has type <class 'int'>
tokenizer.ggml.eos_token_id has type <class 'int'>
tokenizer.chat_template has type <class 'str'>
general.quantization_version has type <class 'int'>
>>> 
```

Seems to work OK so far

**Comment by ddh0** [comment]
With a small patch to llama.py, the new metadata is displayed correctly when loading a model:

<details>
<summary>Click to expand full output</summary>

```
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import llama_cpp
>>> Llama = llama_cpp.Llama('./models/Meta-Llama-3-8B-Instruct-q8_0.gguf')
llama_model_loader: loaded meta data with 22 key-value pairs and 291 tensors from ./models/Meta-Llama-3-8B-Instruct-q8_0.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = Meta-Llama-3-8B-Instruct
llama_model_loader: - kv   2:                          llama.block_count u32              = 32
llama_model_loader: - kv   3:                       llama.context_length u32              = 8192
llama_model_loader: - kv   4:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   7:              llama.attention.head_count_kv u32              = 8
llama_model_loader: - kv   8:                       llama.rope.freq_base f32              = 500000.000000
llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                          general.file_type u32              = 7
llama_model_loader: - kv  11:                           llama.vocab_size u32              = 128256
llama_model_loader: - kv  12:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv  13:                       tokenizer.ggml.model str              = gpt2
llama_model_loader: - kv  14:                         tokenizer.ggml.pre str              = llama-bpe
llama_model_loader: - kv  15:                      tokenizer.ggml.tokens arr[str,128256]  = ["!", "\"", "#", "$", "%", "&", "'", ...
llama_model_loader: - kv  16:                  tokenizer.ggml.token_type arr[i32,128256]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
llama_model_loader: - kv  17:                      tokenizer.ggml.merges arr[str,280147]  = ["Ġ Ġ", "Ġ ĠĠĠ", "ĠĠ ĠĠ", "...
llama_model_loader: - kv  18:                tokenizer.ggml.bos_token_id u32              = 128000
llama_model_loader: - kv  19:                tokenizer.ggml.eos_token_id u32              = 128001
llama_model_loader: - kv  20:                    tokenizer.chat_template str              = {% set loop_messages = messages %}{% ...
llama_model_loader: - kv  21:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q8_0:  226 tensors
llm_load_vocab: special tokens cache size = 256
llm_load_vocab: token to piece cache size = 1.5928 MB
llm_load_print_meta: format           = GGUF V3 (latest)
llm_load_print_meta: arch             = llama
llm_load_print_meta: vocab type       = BPE
llm_load_print_meta: n_vocab          = 128256
llm_load_print_meta: n_merges         = 280147
llm_load_print_meta: n_ctx_train      = 8192
llm_load_print_meta: n_embd           = 4096
llm_load_print_meta: n_head           = 32
llm_load_print_meta: n_head_kv        = 8
llm_load_print_meta: n_layer          = 32
llm_load_print_meta: n_rot            = 128
llm_load_print_meta: n_embd_head_k    = 128
llm_load_print_meta: n_embd_head_v    = 128
llm_load_print_meta: n_gqa            = 4
llm_load_print_meta: n_embd_k_gqa     = 1024
llm_load_print_meta: n_embd_v_gqa     = 1024
llm_load_print_meta: f_norm_eps       = 0.0e+00
llm_load_print_meta: f_norm_rms_eps   = 1.0e-05
llm_load_print_meta: f_clamp_kqv      = 0.0e+00
llm_load_print_meta: f_max_alibi_bias = 0.0e+00
llm_load_print_meta: f_logit_scale    = 0.0e+00
llm_load_print_meta: n_ff             = 14336
llm_load_print_meta: n_expert         = 0
llm_load_print_meta: n_expert_used    = 0
llm_load_print_meta: causal attn      = 1
llm_load_print_meta: pooling type     = 0
llm_load_print_meta: rope type        = 0
llm_load_print_meta: rope scaling     = linear
llm_load_print_meta: freq_base_train  = 500000.0
llm_load_print_meta: freq_scale_train = 1
llm_load_print_meta: n_yarn_orig_ctx  = 8192
llm_load_print_meta: rope_finetuned   = unknown
llm_load_print_meta: ssm_d_conv       = 0
llm_load_print_meta: ssm_d_inner      = 0
llm_load_print_meta: ssm_d_state      = 0
llm_load_print_meta: ssm_dt_rank      = 0
llm_load_print_meta: model type       = 8B
llm_load_print_meta: model ftype      = Q8_0
llm_load_print_meta: model params     = 8.03 B
llm_load_print_meta: model size       = 7.95 GiB (8.50 BPW) 
llm_load_print_meta: general.name     = Meta-Llama-3-8B-Instruct
llm_load_print_meta: BOS token        = 128000 '<|begin_of_text|>'
llm_load_print_meta: EOS token        = 128001 '<|end_of_text|>'
llm_load_print_meta: LF token         = 128 'Ä'
llm_load_print_meta: EOT token        = 128009 '<|eot_id|>'
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:   no
ggml_cuda_init: CUDA_USE_TENSOR_CORES: yes
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 4060 Ti, compute capability 8.9, VMM: yes
llm_load_tensors: ggml ctx size =    0.15 MiB
llm_load_tensors: offloading 0 repeating layers to GPU
llm_load_tensors: offloaded 0/33 layers to GPU
llm_load_tensors:        CPU buffer size =  8137.64 MiB
.........................................................................................
llama_new_context_with_model: n_ctx      = 512
llama_new_context_with_model: n_batch    = 512
llama_new_context_with_model: n_ubatch   = 512
llama_new_context_with_model: flash_attn = 0
llama_new_context_with_model: freq_base  = 500000.0
llama_new_context_with_model: freq_scale = 1
llama_kv_cache_init:  CUDA_Host KV buffer size =    64.00 MiB
llama_new_context_with_model: KV self size  =   64.00 MiB, K (f16):   32.00 MiB, V (f16):   32.00 MiB
llama_new_context_with_model:  CUDA_Host  output buffer size =     0.49 MiB
llama_new_context_with_model:      CUDA0 compute buffer size =   790.81 MiB
llama_new_context_with_model:  CUDA_Host compute buffer size =     9.01 MiB
llama_new_context_with_model: graph nodes  = 1030
llama_new_context_with_model: graph splits = 356
AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 1 | AVX512_VBMI = 1 | AVX512_VNNI = 1 | AVX512_BF16 = 1 | FMA = 1 | NEON = 0 | SVE = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | MATMUL_INT8 = 0 | LLAMAFILE = 1 | 
Model metadata:
  general.architecture: 'llama'
  general.name: 'Meta-Llama-3-8B-Instruct'
  llama.block_count: 32
  llama.context_length: 8192
  llama.embedding_length: 4096
  llama.feed_forward_length: 14336
  llama.attention.head_count: 32
  llama.attention.head_count_kv: 8
  llama.rope.freq_base: 500000.0
  llama.attention.layer_norm_rms_epsilon: 9.999999747378752e-06
  general.file_type: 7
  llama.vocab_size: 128256
  llama.rope.dimension_count: 128
  tokenizer.ggml.model: 'gpt2'
  tokenizer.ggml.pre: 'llama-bpe'
  tokenizer.ggml.tokens: ['!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',',...
  tokenizer.ggml.token_type: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
  tokenizer.ggml.merges: ['Ġ Ġ', 'Ġ ĠĠĠ', 'ĠĠ ĠĠ', 'ĠĠĠ Ġ', 'i n', 'Ġ t', 'Ġ ĠĠĠĠĠĠĠ'...
  tokenizer.ggml.bos_token_id: 128000
  tokenizer.ggml.eos_token_id: 128001
  tokenizer.chat_template: "{% set loop_messages = messages %}{% for message in loop_messages %}{% set content = '<|start_header_id|>' + message['role'] + '<|end_header_id|>\n\n'+ message['content'] | trim + '<|eot_id|>' %}{% if loop.index0 == 0 %}{% set content = bos_token + content %}{% endif %}{{ content }}{% endfor %}{% if add_generation_prompt %}{{ '<|start_header_id|>assistant<|end_header_id|>\n\n' }}{% endif %}"
  general.quantization_version: 2
Available chat formats from metadata: chat_template.default
Guessed chat format: llama-3
>>> 

```
</details>

**Comment by CISC** [comment]
Nice, however I'm still worried that `QuickGGUFReader` will cause some subtle issues due to deviating from the standard at any given time.

At a quick glance I can see that you are not doing any version checks, nor are you taking into account file endianness.

**Comment by ddh0** [comment]
> Nice, however I'm still worried that `QuickGGUFReader` will cause some subtle issues due to deviating from the standard at any given time.
> 
> At a quick glance I can see that you are not doing any version checks, nor are you taking into account file endianness.

Good point about file endianness, I will work on that now.

However, if by version checks you mean GGUF version, I don't think that's necessary - if you take a look at `Llama.__init__`, you'll see the the actual model `_LlamaModel` is created before `Llama.metadata` is set. So, if the code in `QuickGGUFReader` reached, the model is already successfully loaded - so I don't see a point in enforcing version checks in that way.

If that's not what you meant, could you please clarify?

**Comment by ddh0** [comment]
> Models are little-endian by default. They can also come in big-endian for use with big-endian computers; in this case, all values (including metadata values and tensors) will also be big-endian. At the time of writing, there is no way to determine if a model is big-endian; this may be rectified in future versions. If no additional information is provided, assume the model is little-endian.

(source: [GGUF format spec](https://github.com/ggerganov/ggml/blob/master/docs/gguf.md))

The change I just made supports little or big endian GGUF files. It does so by assuming that the GGUF file is of the same endianness as the host machine. This assumption is safe to make because, at this point in the code, the model itself is already successfully loaded, so it must be the same endianness as the host. Per the format specification, I think this is a pretty reasonable solution.

**Comment by CISC** [comment]
Since `QuickGGUFReader` only works with v3 (v1 won't work at all I think, and v2 will be subtly broken) files you should definitely check the version, additionally there's no way to know if v4 will be backwards compatible or not.

You can simplify your code by using the native byteorder marker (`=`). :)

**Comment by ddh0** [comment]
Gotcha. I can work on supporting GGUFv2. v1 will remain unsupported.

**Comment by ddh0** [comment]
GGUFv2 support is **not** working yet. I'm using this model for testing: [fgewfskjfsd/Wizard-Vicuna-13B-Uncensored-SuperHOT-8K-GGUFv2](https://huggingface.co/fgewfskjfsd/Wizard-Vicuna-13B-Uncensored-SuperHOT-8K-GGUFv2).

**Comment by ddh0** [comment]
GGUFv2 support is now fully working. Tested with `mistral-7b-instruct-v0.1.Q4_K_S.gguf`, `mistral-7b-phibrarian-32k.Q4_K_S.gguf`, and `wizard-vicuna-13b-uncensored-superhot-8k.Q4_K_S.gguf` (all GGUFv2 models).

**Comment by CISC** [comment]
Looking good, however there are a couple of issues:

* You will never find `vendor` in a regular installation, since you're not really using gguf-py I suggest just hardcoding the `GGUFValueType`s
* The current `metadata` retrieved via llama.cpp API are all string, this means if you replace the `metadata` dict directly as you do now it's a breaking change. I think you need to leave the old one as-is and add a new `_LlamaModel` method and `Llama` property instead.

**Comment by ddh0** [comment]
> The current metadata retrieved via llama.cpp API are all string, this means if you replace the metadata dict directly as you do now it's a breaking change. I think you need to leave the old one as-is and add a new _LlamaModel method and Llama property instead.

I will wait for @abetlen to give his thoughts on this

**Comment by ddh0** [comment]
On a different note, I do notice these lines in llama.py:

```python
        # Unfortunately the llama.cpp API does not return metadata arrays, so we can't get template names from tokenizer.chat_templates
        template_choices = dict((name[10:], template) for name, template in self.metadata.items() if name.startswith("tokenizer.chat_template."))
```

I'm guessing this could be simplified if `QuickGGUFReader` is used, but I'm not sure what that would look like

**Comment by ExtReMLapin** [comment]
based

**Pull request closed without merging**
