### PR TITLE
Workflow speed up - POST PART 1

### PR DESCRIPTION
**Pull request by Smartappli**

### CODE REVIEW

**Comment by abetlen** [comment]
@Smartappli I was looking at this a few months ago as well because uv is a pretty amazing tool. The issue I ran into however is that it doesn't log the output of subcommands (ie cmake), so if the build fails it's kinda tough to debug.

[Related Issue](https://github.com/astral-sh/uv/issues/1567) and [PR](https://github.com/astral-sh/uv/pull/2156)

**Comment by Smartappli** [comment]
@abetlen Thank you for your advice. I think I have solved this problem.

**Comment by abetlen** [comment]
I tried setting `RUST_LOG=trace` locally but I still don't see the actual logs from the cmake build system.

**Comment by Smartappli** [comment]
Ping @abetlen

**Review by abetlen — APPROVED** [review]

**Comment by abetlen** [comment]
@Smartappli thank you for your contribution and patience on this one, merging now that uv has support for the build logs with `--verbose`

**Pull request merged**
