### PR TITLE
Update build-wheels-metal.yaml

### PR DESCRIPTION
**Pull request by Smartappli**
Bump actions/setup-python@v4 to v5
Bump softprops/action-gh-release@v1 to v2

### CODE REVIEW

**Comment by Smartappli** [comment]
Build Test: https://github.com/Smartappli/llama-cpp-python/actions/runs/8855666619

**Comment by Smartappli** [comment]
Build Test: https://github.com/Smartappli/llama-cpp-python/actions/runs/8856194118

**Comment by abetlen** [comment]
@Smartappli thank you so much for this and for running those tests however I think the runs aren't actually using the updated workflow files (if you check Run Details > Workflow File on the bottom left it's still using `actions/setup-python@v4`).

**Comment by Smartappli** [comment]
> @Smartappli thank you so much for this and for running those tests however I think the runs aren't actually using the updated workflow files (if you check Run Details > Workflow File on the bottom left it's still using `actions/setup-python@v4`).

@abetlen Fixed: https://github.com/Smartappli/llama-cpp-python/actions/runs/8857922679

**Comment by Smartappli** [comment]
Build Test: https://github.com/Smartappli/llama-cpp-python/actions/runs/8858016391

**Pull request merged**
