### PR TITLE
Add self extend support

### PR DESCRIPTION
**Pull request by Josh-XT**
Add self extend support
- More info in https://github.com/ggerganov/llama.cpp/pull/4815

### CODE REVIEW

**Comment by Josh-XT** [comment]
I might still be missing something, still checking.

**Comment by Josh-XT** [comment]
Haven't had time to finish the rest of this, got pulled away in the middle! Sorry - I'll reopen when ready.

**Comment by jshph** [comment]
Hey @Josh-XT thanks for taking a stab. Curious if the implementation is in the right direction here, I was poking at it yesterday and saw the Params struct being modified. I wonder if that'd affect the parsing of args downstream.

**Comment by Josh-XT** [comment]
> Hey @Josh-XT thanks for taking a stab. Curious if the implementation is in the right direction here, I was poking at it yesterday and saw the Params struct being modified. I wonder if that'd affect the parsing of args downstream.

I was attempting to follow the changes made on the cpp repo but while hanging out with my 4 year old, then he made a mess and I had to stop. 🤣 I was trying to do the cpp server example at the same time when my plans were changed. The implementation is pretty straightforward. I think the `grp-attn-n` and `grp-attn-w` could (and probably will) be automated away.

**Comment by ExtReMLapin** [comment]
Any update on this ?

**Pull request closed without merging**
