### PR TITLE
Add support for cuda 12.4.1

### PR DESCRIPTION
**Pull request by Smartappli**
Add support for cuda 12.4.1

Bump actions/setup-python@v4 to v5 (Deprecated)
Bump conda-incubator/setup-miniconda@v2.2.0 to v3.0.4 (Depecation of Node.js 16)
Bump actions/cache@v3.3.2 to v4.0.2 (Deprecation of Node.js 16)
Bump softprops/action-gh-release@v1 to v2 (Deprecation of Node.js 16)

### CODE REVIEW

**Comment by Smartappli** [comment]
Build Test: https://github.com/Smartappli/llama-cpp-python/actions/runs/8855583838

**Comment by Smartappli** [comment]
Build Test: https://github.com/Smartappli/llama-cpp-python/actions/runs/8856146033

**Comment by Smartappli** [comment]
Build Test: https://github.com/Smartappli/llama-cpp-python/actions/runs/8858029376

**Comment by abetlen** [comment]
@Smartappli happy to add support for building the 12.4 wheels, can I ask what's the reasoning for changing the link to the fork of `cuda-toolkit`?

**Comment by Smartappli** [comment]
Build Test: https://github.com/Smartappli/llama-cpp-python/actions/runs/8864805947

**Comment by Smartappli** [comment]
> @Smartappli happy to add support for building the 12.4 wheels, can I ask what's the reasoning for changing the link to the fork of `cuda-toolkit`?

Link reverted

**Comment by abetlen** [comment]
@Smartappli thank you!

**Pull request merged**
